### ISSUE TITLE
Bump version number (to 2.1.1?)

### ISSUE THREAD

**Issue by luizirber** [PROSIC/prosic2#1]
Currently the bioconda recipe is failing due to changes in the `rand` crate:
https://github.com/bioconda/bioconda-recipes/blob/80f482466ec39833454d745c4f2e437de0bf6120/build-fail-blacklist#L35

But the master branch works fine, so maybe tag it as 2.1.1?

**Comment by johanneskoester** [comment]
Thanks for the heads up. We will do a new release soon.

**Comment by johanneskoester** [comment]
We have that release now, which is actually the final one, since prosic is now varlociraptor.

**Comment by dlaehnemann** [comment]
@johanneskoester has just released a new version and there is an attempt at unblacklisting:
https://github.com/bioconda/bioconda-recipes/pull/17807
